<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../AccessControl.Core/AccessControl.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="PhraseForm.cs"><SubType>Form</SubType></Compile>
    <Compile Update="PhraseForm.Designer.cs"><DependentUpon>PhraseForm.cs</DependentUpon></Compile>
    <Compile Update="LoginForm.cs"><SubType>Form</SubType></Compile>
    <Compile Update="LoginForm.Designer.cs"><DependentUpon>LoginForm.cs</DependentUpon></Compile>
    <Compile Update="PasswordForm.cs"><SubType>Form</SubType></Compile>
    <Compile Update="PasswordForm.Designer.cs"><DependentUpon>PasswordForm.cs</DependentUpon></Compile>
    <Compile Update="AddUserForm.cs"><SubType>Form</SubType></Compile>
    <Compile Update="AddUserForm.Designer.cs"><DependentUpon>AddUserForm.cs</DependentUpon></Compile>
    <Compile Update="UserSettingsForm.cs"><SubType>Form</SubType></Compile>
    <Compile Update="UserSettingsForm.Designer.cs"><DependentUpon>UserSettingsForm.cs</DependentUpon></Compile>
    <Compile Update="MainForm.cs"><SubType>Form</SubType></Compile>
    <Compile Update="MainForm.Designer.cs"><DependentUpon>MainForm.cs</DependentUpon></Compile>
  </ItemGroup>
</Project>
